### ISSUE TITLE
Caddy returns 200 when 5xx fom upstream

### ISSUE THREAD

**Issue by ishuvalov** [caddyserver/cache-handler#25]
When I use 'cache' handler, Caddy always returns status code 200 and empty response whenever upstream is unavailable or returns 5xx errors.
Please advice how can upstream errors can be passed through the cache. Thanks.

**Comment by mholt** [comment]
That's just Caddy's default response. Chances are a misconfiguration. What is your config and what is a `curl -v` command that reproduces the 200 response?

**Comment by ishuvalov** [comment]
Thank you for the reply.
If I remove cache handler from the handlers chain, I get normal 502 from missing upstream.
A also experimented with `curl`:

```
$ curl -v http://localhost/
*   Trying 127.0.0.1:80...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: Caddy
< Date: Mon, 21 Mar 2022 15:16:21 GMT
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```

And doing this way I get proper 502.
```
$ curl -v -H "Pragma: no-cache"  http://localhost/
*   Trying 127.0.0.1:80...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.79.1
> Accept: */*
> Pragma: no-cache
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 502 Bad Gateway
< Cache-Status: Souin; fwd=uri-miss
< Server: Caddy
< Date: Mon, 21 Mar 2022 15:19:09 GMT
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```

**Comment by ishuvalov** [comment]
Here is my config. (I find YAML more human friendly than JSON)
```
apps:
  http:
    servers:
      srv_cache_api:
        listen:
          - :2020
        routes:
          - match:
              - path:
                  - /cache-api*
            handle:
              - handler: cache
      srv_main:
        listen:
          - :80
        automatic_https:
          disable: true
          disable_redirects: true
        routes:
          - handle:
            - handler: cache
            - handler: encode
              encodings:
                gzip: {}
                zstd: {}
              prefer:
                - zstd
                - gzip
            - handler: reverse_proxy
              upstreams:
                - dial: "#{$UPSTREAM}"
        logs:
          default_logger_name: log0

  cache:
    TTL: 1m
    stale: 1m
    log_level: INFO
    api:
      basepath: /cache-api
      souin:
        basepath: /souin
        enable: true
      prometheus:
        basepath: /prometheus
        enable: true

logging:
  logs:
    default:
      writer:
        output: stdout
      level: INFO
      exclude:
        - http.log.access.log0
    error_log:
      writer:
        output: stderr
      level: ERROR
    access:
      writer:
        filename: /var/log/caddy/access.log
        output: file
      level: INFO
      include:
        - http.log.access.log0
admin:
  listen: 0.0.0.0:2019
```

I also would like to mention, that I tried do build Caddy with two variants of plugin:
`xcaddy build --with github.com/caddyserver/cache-handler` - this one always returns 200 when missing the upstream, even ignoring "Pragma: no-cache" header
`xcaddy build --with github.com/darkweak/souin/plugins/caddy` - this returns statuses like in examples I've posted above.

I hope this helps. Thanks.
